version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx/
    networks:
      - dev


  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - "./:/var/www/"
    depends_on:
      - nginx
    networks:
      - dev
    command: npm run build